name: demo github action example

on: 
  workflow_dispatch:

jobs:
  my_demo_job:
    name: Example shell command execution
    runs-on: ubuntu-latest

    steps:
      - name: shell command
        run: echo "Hello world!"
