name: demo github action example

on: 
  workflow_dispatch:

jobs:
  my_demo_job:
    name: demo-job-1
    runs-on: ubuntu-latest

    steps:
      - name: shell command
        run: echo "Hello world!"
