name: Workflow-03
on:
  workflow_dispatch: 
jobs:
  prod-deploy:
    if: ${{ github.repository == 'chandrashekarhamse/Hello-world' }}
    runs-on: ubuntu-latest
    steps:
    - name: check npm version 
      run: npm --version

