name: Dependent jobs

on:
  workflow_dispatch: 

jobs:
  job_1:
    name: This is job 1
    runs-on: ubuntu-latest
    steps:
      - name: running job 1
        run: echo "this is job 1"
  job_2:
    needs: job_1
    name: This is job 2
    runs-on: ubuntu-latest
    steps:
      - name: running job 2
        run: echo "this is job2 which ran after job 1"
  job_3:
    needs: [job_1, job_2]
    name: This is job 3
    runs-on: ubuntu-latest
    steps:
      - name: running job 3
        run: echo "this is job3 running after successful completion of job1 and job2"
