name: container workflow
on: 
  workflow_dispatch:

concurrency: 
  group: demo-group
  cancel-in-progress: false

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_vol:/volume_mount
      options: --cpus 1
    steps:
      - name: check docker hostname
        run: hostname
      - name: check the filesystem
        run: df -h
