name: Dependent job test

on: 
  workflow_dispatch:

jobs:
  job_1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Run job 1
        run: echo "This is job 1"
  job_2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - name: Run job2
        run: echo "This is job 2"
  job_3:
    if: ${{ always() }}
    needs: [job_1,job_2]
    name: Job3
    runs-on: ubuntu-latest
    steps:
      - name: Run job3
        run: echo "This is job 3"
